return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "快睡吧！",
			GENERIC = "怎么刮？",
			NOBITS = "原来毛下是肉，嘿嘿嘿...",
		},
		STORE =
		{
			GENERIC = "前辈快来呀，拿不完啊！",
			NOTALLOWED = "我怎么可能拿得动啊！",
		},
		RUMMAGE =
		{	
			GENERIC = "我拒绝",	
		},
        COOK =
        {
            GENERIC = "唉呀呀，怎么不行啊",
            TOOFAR = "诶诶诶，我的食物！",
        },
        GIVE =
        {
            DEAD = "我要活下去，前辈在等我",
            SLEEPING = "关心关心",
            BUSY = "再试试吧",
        },
        WRITE =
        {
            GENERIC = "我觉得还行",
        },
		REPAIRBOAT = 
		{
			GENERIC = "修好了，好棒！",
		},
		TEACH =
        {
            KNOWN = "我知道我知道！",
            CANTLEARN = "我也想知道啊",
        },
	},
	ACTIONFAIL_GENERIC = "sorry！",
	ANNOUNCE_MAGIC_FAIL = "费时又费力",
	
	ANNOUNCE_ADVENTUREFAIL = "再试试吧",
	ANNOUNCE_BEES = "蜜蜂啊！！！快跑，前辈！",
	ANNOUNCE_BOOMERANG = "好好玩啊",
	ANNOUNCE_CHARLIE = "前辈那是什么？",
	ANNOUNCE_CHARLIE_ATTACK = "真的好疼啊〒▽〒",
	ANNOUNCE_COLD = "冷冷冷！！！",
	ANNOUNCE_HOT = "热热热！！！",
	ANNOUNCE_CRAFTING_FAIL = "材料不够啊，前辈帮我",
	ANNOUNCE_DEERCLOPS = "什么东西啊？？？",
	ANNOUNCE_DUSK = "前辈在哪啊，天黑了，啊啊啊！！！",
	ANNOUNCE_EAT =
	{
		GENERIC = "好香~~哈哈",
		PAINFUL = "这是神马？",
		SPOILED = "哇，我想吐",
		STALE = "不好吃了啊，前辈快请我吃大餐",
		INVALID = "居然不能吃？？",
		YUCKY = "这个也太难吃了吧",
	},
	ANNOUNCE_ENTER_DARK = "前辈，我的眼镜呢？",
	ANNOUNCE_ENTER_LIGHT = "哈哈，找到眼镜啦！",
	ANNOUNCE_FREEDOM = "自由",
	ANNOUNCE_HIGHRESEARCH = "我真聪明，嘻嘻！",
	ANNOUNCE_HOUNDS = "狗等于肉，嘿嘿嘿，快来吧",
	ANNOUNCE_WORMS = "恶心！",
	ANNOUNCE_SHARX = "前辈，我...我想要航空母舰",
	ANNOUNCE_HUNGRY = "前辈我好饿啊",
	ANNOUNCE_HUNT_BEAST_NEARBY = "找到肉了！！",
	ANNOUNCE_HUNT_LOST_TRAIL = "啊咧？消失了？",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "可恶的下雨天！",
	ANNOUNCE_INV_FULL = "前辈快来呀，拿不完啊",
	ANNOUNCE_KNOCKEDOUT = "我的头！",
	ANNOUNCE_LOWRESEARCH = "没什么X用",
	ANNOUNCE_MOSQUITOS = "你敢吸我的血，我敬你是条汉子",
	ANNOUNCE_NODANGERSLEEP = "好害怕，睡不着",
	ANNOUNCE_NODAYSLEEP = "现在是白天啊",
	ANNOUNCE_NODAYSLEEP_CAVE = "我现在不累，没关系",
	ANNOUNCE_NOHUNGERSLEEP = "咕咕咕~~~唉，讨厌",
	ANNOUNCE_NOSLEEPONFIRE = "这样不行啊",
	ANNOUNCE_NODANGERSIESTA = "好害怕，睡不着 δ△δ",
	ANNOUNCE_NONIGHTSIESTA = "晚上就要睡在床上，哈哈",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "啊不，不行，我要床！",
	ANNOUNCE_NOHUNGERSIESTA = "咕咕咕~~~唉，讨厌",
	ANNOUNCE_NO_TRAP = "前辈我厉害吧，嘻嘻",
	ANNOUNCE_PECKED = "呜呜呜，前辈帮我",
	ANNOUNCE_QUAKE = "什...什么！？",
	ANNOUNCE_RESEARCH = "学习使我快乐",
	ANNOUNCE_SHELTER = "大树你最好了",
	ANNOUNCE_THORNS = "啊！！！",
	ANNOUNCE_BURNT = "啊！？呜呜呜，前辈！！！",
	ANNOUNCE_TORCH_OUT = "唉，用完了",
	ANNOUNCE_FAN_OUT = "啊咧！？没了",
    ANNOUNCE_COMPASS_OUT = "啧啧，质量好差啊",
	ANNOUNCE_TRAP_WENT_OFF = "哦哦",
	ANNOUNCE_UNIMPLEMENTED = "哦，好像还没呢",
	ANNOUNCE_WORMHOLE = "呜啊，恶心",
	ANNOUNCE_CANFIX = "还差什么？",
	ANNOUNCE_ACCOMPLISHMENT = "我为何这么熟练",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "前辈快看，厉害吧",	
	ANNOUNCE_INSUFFICIENTFERTILIZER = "哎呀，我也饿",
	ANNOUNCE_TOOL_SLIP = "哇，好滑。",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "呜呜呜，吓死我了！！！",

	ANNOUNCE_DAMP = "哎哎哎，好多水啊！",
	ANNOUNCE_WET = "前辈我一身都湿透了，别盯着我！",
	ANNOUNCE_WETTER = "前辈转过去，我想换衣服",
	ANNOUNCE_SOAKED = "我感觉我要融化了",

	ANNOUNCE_TREASURE = "哦耶！宝藏，嘿嘿嘿...",
	ANNOUNCE_MORETREASURE = "啊咧，还有？",
	ANNOUNCE_OTHER_WORLD_TREASURE = "唉呀，什么都没有",
	ANNOUNCE_OTHER_WORLD_PLANT = "怎么可能会活",

	ANNOUNCE_MESSAGEBOTTLE =
	{
		"看不清啊，擦擦眼镜",
	},
	ANNOUNCE_VOLCANO_ERUPT = "怎么办怎么办？！？！前辈！！！",
	ANNOUNCE_MAPWRAP_WARN = "怪物！？",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "朦朦胧胧",
	ANNOUNCE_MAPWRAP_RETURN = "啊~~~前辈我脚上有什么东西在动！！！",
	ANNOUNCE_CRAB_ESCAPE = "哇哈哈哈，肉肉！",
	ANNOUNCE_TRAWL_FULL = "哈哈，网里满了，吃鱼！",
	ANNOUNCE_BOAT_SINKING = "前辈，好像在漏水啊",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "赶...赶紧上岸！！！",
	ANNOUNCE_WAVE_BOOST = "哦~哦~",

	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "气泡！？鱼！？肉！？",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "喂，别跑啊",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "哦哦哦，波涛汹涌",


	BATTLECRY =
	{
		GENERIC = "站住，别跑，打你!",
		PIG = "移动的大肉块！我要",
		PREY = "食物！肉！",
		SPIDER = "来吧，小家伙",
		SPIDER_WARRIOR = "最讨厌就是你",
	},
	COMBAT_QUIT =
	{
		GENERIC = "拜拜！",
		PIG = "唉唉唉，别走啊，我的肉啊",
		PREY = "干嘛走这么快啊！",
		SPIDER = "下次就是一块怪兽肉了",
		SPIDER_WARRIOR = "明明也只是怪兽肉",
	},

	DESCRIBE =
	{
        WILDBOREGUARD = "这值得保护吗",
        GLOMMER = "嘿，前辈，这个好可爱呀",
        GLOMMERFLOWER = 
        {
        	GENERIC = "这个花可以吃吗？",
        	DEAD = "啊咧，怎么枯萎了？",
        },
        GLOMMERWINGS = "这么小的翅膀能飞吗",
        GLOMMERFUEL = "前辈这个好像能吃！！！",
        BELL = "滴铃滴铃滴铃滴铃...",
        STATUEGLOMMER = 
        {	
        	GENERIC = "这个雕像好可爱呀！",
        	EMPTY = "才...才不是我弄坏的...",
    	},

		LAVA_POND_ROCK = "就像任何一个地方一样。",
		LAVA_POND_ROCK2 = "就像任何一个地方一样。",
		LAVA_POND_ROCK3 = "就像任何一个地方一样。",
		LAVA_POND_ROCK4 = "就像任何一个地方一样。",
		LAVA_POND_ROCK5 = "就像任何一个地方一样。",
		LAVA_POND_ROCK6 = "就像任何一个地方一样。",
		LAVA_POND_ROCK7 = "就像任何一个地方一样。",

		WEBBERSKULL = "这...这是什么啊？？前辈我好怕",
		WORMLIGHT = "好像味道不错哟",
		WORMLIGHT_LESSER = "怎么这样了？",
		WORM =
		{
		    PLANT = "前辈我要吃那个！",
		    DIRT = "这个真是又恐怖又恶心",
		    WORM = "啊啊啊！！！是个大蚯蚓！",
		},
		WORMLIGHT_PLANT = "前辈我要吃那个！",
		MOLE =
		{
			HELD = "前辈我想...吃！",
			UNDERGROUND = "它来了，来了，肉！",
			ABOVEGROUND = "抓住你了！",
		},
		MOLEHILL = "前辈你在里面吗？",
		MOLEHAT = "呃~~~好臭啊",

		EEL = "哇哇哇！前辈，我要吃！",
		EEL_COOKED = "嘿嘿嘿！",
		UNAGI = "我要开动了",
		EYETURRET = "它好恶心啊",
		EYETURRET_ITEM = "不错，其实也没啥用",
		MINOTAURHORN = "放开我，我想试试味",
		MINOTAURCHEST = "我可是欧洲人！",
		THULECITE_PIECES = "又不能吃，真是的",
		POND_ALGAE = "配点肉就更好了",
		GREENSTAFF = "样子还不错",
		POTTEDFERN = "这是？！盆栽？！吗？",

		THULECITE = "前辈，这个是不是调味剂啊",
		ARMORRUINS = "前辈这个光好奇怪啊",
		RUINS_BAT = "哎哟，前辈，它扎手",
		RUINSHAT = "前辈怎么样？",
		NIGHTMARE_TIMEPIECE =
		{
			CALM = "很安静",
			WARN = "我有不好的预感",
			WAXING = "完了！！！前辈！",
			STEADY = "好稳！",
			WANING = "唉，吓死我了",
			DAWN = "过去了",
			NOMAGIC = "没有能量涌动",
		},
		BISHOP_NIGHTMARE = "什么嘛，又不能吃",
		ROOK_NIGHTMARE = "它...它过来了！前辈！",
		KNIGHT_NIGHTMARE = "不能吃，不愉快",
		MINOTAUR = "可算是找到你了",
		SPIDER_DROPPER = "有这个品种？？？",
		NIGHTMARELIGHT = "前辈，这个有什么用啊",
		NIGHTSTICK = "是电！",
		GREENGEM = "很好看嘛",
		RELIC = "这都是什么年代的啊",
		RUINS_RUBBLE = "前辈，这个好像可以修好的",
		MULTITOOL_AXE_PICKAXE = "明明我的厉害一些",
		ORANGESTAFF = "前辈我们来玩捉迷藏吧",
		YELLOWAMULET = "前辈，快看，我会发光",
		GREENAMULET = "划算吗？",
		SLURPERPELT = "这个我不想吃",		

		SLURPER = "看看谁吃谁",
		SLURPER_PELT = "这个我不想吃",	
		ARMORSLURPER = "管用吗，我还想吃",
		ORANGEAMULET = "快帮我捡肉，前辈也来嘛",
		YELLOWSTAFF = "小星星",
		YELLOWGEM = "真漂亮",
		ORANGEGEM = "这个也漂亮",
		TELEBASE = 
		{
			VALID = "哈哈，出发！",
			GEMS = "怎么没用了？",
		},
		GEMSOCKET = 
		{
			VALID = "完成了",
			GEMS = "前辈，帮我！",
		},
		STAFFLIGHT = "这个好危险啊",
	
        ANCIENT_ALTAR = "简直完美",

        ANCIENT_ALTAR_BROKEN = "哦，是坏的",

        ANCIENT_STATUE = "不好意思，拆！",

        LICHEN = "生命顽强啊，和前辈一样，嘿嘿",
		CUTLICHEN = "我想马上尝尝",

		CAVE_BANANA = "哇，是香蕉",
		CAVE_BANANA_COOKED = "香蕉要烤吗，不管了",
		CAVE_BANANA_TREE = "，前辈，我要吃香蕉",
		ROCKY = "这么有这个东西的",
		
		COMPASS =
		{
			GENERIC="我这是向哪里?",
			N = "北",
			S = "南",
			E = "东",
			W = "西",
			NE = "东北",
			SE = "东南",
			NW = "西北",
			SW = "西南",
		},

		HOUNDSTOOTH="牙齿？",
		ARMORSNURTLESHELL="一点也不好看",
		BAT="讨厌的家伙",
		BATBAT = "我的食物这么这样了？",
		BATWING="感觉不错",
		BATWING_COOKED="赶快让我试试！",
		BATCAVE = "嘘！前辈小声点",
		BEDROLL_FURRY="睡觉！哦耶",
		BUNNYMAN="这真是又爱又恨啊",
		FLOWER_CAVE="漂亮又美味",
		FLOWER_CAVE_DOUBLE="漂亮又美味",
		FLOWER_CAVE_TRIPLE="漂亮又美味",
		GUANO= "恶心！",
		LANTERN= "前辈帮我拿一下好吗？",
		LIGHTBULB= "吃一口试试",
		MANRABBIT_TAIL= "毛茸茸，好舒服",
		MUSHTREE_TALL  = "越大越好吃",
		MUSHTREE_MEDIUM= "前辈帮我摘蘑菇",
		MUSHTREE_SMALL = "蘑菇蘑菇",
		MUSHTREE_TALL =
		{
            GENERIC = "越大越好吃",
            BLOOM = "有点臭啊",
        },
		MUSHTREE_MEDIUM = 
		{
            GENERIC = "这个不能吃吗？",
            BLOOM = "好像不能吃啊",
        },
		MUSHTREE_SMALL = 
		{
            GENERIC = "前辈这个能吃吗",
            BLOOM = "前辈你先尝尝",
        },
        MUSHTREE_TALL_WEBBED = "可恨的蜘蛛",
        SPORE_TALL = "闪闪发光",
        SPORE_MEDIUM = "闪闪发光",
        SPORE_SMALL = "闪闪发光",
        SPORE_TALL_INV = "哈哈，它在我包里也发光呢",
        SPORE_MEDIUM_INV = "哈哈，它在我包里也发光呢",
        SPORE_SMALL_INV = "哈哈，它在我包里也发光呢",
		RABBITHOUSE=
		{
			GENERIC = "好大的胡萝卜啊，前辈，我想要",
			BURNT = "烤胡萝卜？",
		},
		SLURTLE="讨厌，恶心",
		SLURTLE_SHELLPIECES="好硬啊",
		SLURTLEHAT= "我觉得我要洗一下头发",
		SLURTLEHOLE= "里面还有吗？",
		SLURTLESLIME= "我有点想吐",
		SNURTLE= "恶心的玩意",
		SPIDER_HIDER= "有本事别躲啊",
		SPIDER_SPITTER= "什么品种，这么厉害",
		SPIDERHOLE= "快出来，我知道你在里面",
		SPIDERHOLE_ROCK = "这个给人一种年代感",
		STALAGMITE= "又黑又硬，能吃就好了",
		STALAGMITE_FULL= "又黑又硬，能吃就好了",
		STALAGMITE_LOW= "又黑又硬，能吃就好了",
		STALAGMITE_MED= "又黑又硬，能吃就好了",
		STALAGMITE_TALL= "石头吃了是不是补钙？",
		STALAGMITE_TALL_FULL= "石头吃了是不是补钙？",
		STALAGMITE_TALL_LOW= "石头吃了是不是补钙？",
		STALAGMITE_TALL_MED= "石头吃了是不是补钙？",

		TURF_CARPETFLOOR = "只是地皮而已",
        TURF_CHECKERFLOOR = "只是地皮而已",
		TURF_DIRT = "只是地皮而已.",
		TURF_FOREST = "只是地皮而已",
		TURF_GRASS = "只是地皮而已",
		TURF_MARSH = "只是地皮而已",
		TURF_ROAD = "只是地皮而已",
		TURF_ROCKY = "只是地皮而已",
		TURF_SAVANNA = "只是地皮而已",
		TURF_WOODFLOOR = "只是地皮而已",

		TURF_CAVE="只是地皮而已",
		TURF_FUNGUS="只是地皮而已",
		TURF_SINKHOLE="只是地皮而已",
		TURF_UNDERROCK="只是地皮而已",
		TURF_MUD="只是地皮而已",

		TURF_DECIDUOUS = "只是地皮而已",
		TURF_SANDY = "只是地皮而已",
		TURF_BADLANDS = "只是地皮而已",
		TURF_DESERTDIRT = "只是地皮而已",
		TURF_FUNGUS_GREEN = "只是地皮而已",
		TURF_FUNGUS_RED = "只是地皮而已",
		TURF_DRAGONFLY = "只是地皮而已",

		POWCAKE = "快给我试试",
        CAVE_ENTRANCE = 
        {
            GENERIC="里面会不会有好吃的啊？",
            OPEN = "前辈你先下去",
        },
        CAVE_EXIT = "这怎么上去啊",
        CAVE_ENTRANCE_OPEN = 
        {
            GENERIC = "里面会不会有好吃的啊？",
            OPEN = "里面会不会有好吃的啊？",
        },
        CAVE_EXIT = 
        {
            GENERIC = "啊！？不会上不去吧",
            OPEN = "前辈拉我一把",
        },
		MAXWELLPHONOGRAPH = "不太好听啊",
		BOOMERANG = "飞！",
		PIGGUARD = "又是一块肉",
		ADVENTURE_PORTAL = "我不想去啊",
		AMULET = "这么大的护身符？",
		ANIMAL_TRACK = "这是肉的脚印",
		ARMORGRASS = "又难看又没用",
		ARMORMARBLE = "好重啊！",
		ARMORWOOD = "木头行不行啊",
		ARMOR_SANITY = "感觉没穿一样",
		ASH =
		{
			GENERIC = "烈火带走了一切",
			REMAINS_GLOMMERFLOWER = "为什么会这样？",
			REMAINS_EYE_BONE = "为什么会这样？",
			REMAINS_THINGIE = "为什么会这样？",
		},
		AXE = "我是不会做它的",
		BABYBEEFALO = "快长大吧，越大肉越多",
		BACKPACK = "最实用！没有之一",
		BACONEGGS = "蛋和肉什么的最喜欢了",
		BANDAGE = "很干净？",
		BASALT = "这个好硬啊",
		BATBAT = "我的食物这么这样了？",
		BEARDHAIR = "幸好我不长胡子",
		BEARGER = "大熊有大肉",
		BEARGERVEST = "肯定很值钱，拿去换盆栽",
		ICEPACK = "食物背包，哈哈",
		BEARGER_FUR = "简直就是盆栽",
		BEDROLL_STRAW = "睡觉！哦耶",
		BEE =
		{
			GENERIC = "前辈我要吃蜂蜜",
			HELD = "快跑",
		},
		BEEBOX =
		{
			FULLHONEY = "真想一起吃了",
			GENERIC = "蜜蜂快快快！",
			NOHONEY = "唉！什么都没有",
			SOMEHONEY = "哈哈，有一点了",
			BURNT = "到底是谁干的！？",
		},
		BEEFALO =
		{
			FOLLOWER = "快来大肉块",
			GENERIC = "牛就是大肉块",
			NAKED = "它身上只剩下肉了",
			SLEEPING = "我也想睡觉",
		},
		BEEFALOHAT = "这帽子不好看却很有用",
		BEEFALOWOOL = "为什么毛不能吃啊",
		BEEHAT = "蜂蜜，哦不，蜜蜂，我们一决胜负吧！",
		BEEHIVE = "这个感觉就是蜜桶",
		BEEMINE = "前辈，小心这个",
		BEEMINE_MAXWELL = "前辈快跑，这个有问题",
		BERRIES = "简直完美至极",
		BERRIES_COOKED = "感觉生吃好一点吧",
		BERRYBUSH =
		{
			BARREN = "这么这样了",
			WITHERED = "别啊，为什么？",
			GENERIC = "前辈快帮我摘！",
			PICKED = "长长长！！！",
		},
		BIGFOOT = "大脚肉？",
		BIRDCAGE =
		{
			GENERIC = "放一只可爱的小鸟进去",
			OCCUPIED = "我担心我会吃了它的",
			SLEEPING = "哈哈，它在睡觉，好可爱",
			HUNGRY = "不可能，它不会比我还饿",
			STARVING = "我才没有吃掉它的食物呢！",
			DEAD = "呜呜呜，我的小鸟死了",
			SKELETON = "全完了！",
		},
		BIRDTRAP = "抓鸟，吃鸟！",
		CAVE_BANANA_BURNT = "哦，天哪，我的香蕉",
		BIRD_EGG = "蛋和肉最配",
		BIRD_EGG_COOKED = "再来点肉吧！",
		BISHOP = "为什么不能吃啊",
		BLOWDART_FIRE = "不会把家烧了吧",
		BLOWDART_SLEEP = "这个有用吗",
		BLOWDART_PIPE = "拿去换肉",
		BLUEAMULET = "冰冰的，滑滑的",
		BLUEGEM = "前辈，你摸摸，好凉快啊",
		BLUEPRINT = "我要学习",
		BELL_BLUEPRINT = "小铃铛，摇一摇",
		BLUE_CAP = "吃吃吃",
		BLUE_CAP_COOKED = "变化好大呀，不过还是吃",
		BLUE_MUSHROOM =
		{
			GENERIC = "只是一个该被吃的蘑菇",
			INGROUND = "快出来呀",
			PICKED = "好无聊，这么就没了",
		},
		BOARDS = "木板怎么了？",
		BOAT = "征服海洋",
		BONESHARD = "你是渣渣骨",
		BONESTEW = "这个骨头怎么出现的？",
		BUGNET = "前辈和我一起抓蝴蝶吃吧",
		BUSHHAT = "前辈来玩躲猫猫吧",
		BUTTER = "噢噢噢！！！我等不及了",
		BUTTERFLY =
		{
			GENERIC = "前辈快看，是蝴蝶！",
			HELD = "哈哈，我抓到它了",
		},
		BUTTERFLYMUFFIN = "是正常人都把持不住的",
		BUTTERFLYWINGS = "我其实想知道这个为什么能吃",
		BUZZARD = "秃...秃",
		CACTUS = 
		{
			GENERIC = "仙人掌我也要吃",
			PICKED = "谁要你刺我的",
		},
		CACTUS_MEAT_COOKED = "好香！",
		CACTUS_MEAT = "好多刺啊，难道是吃鱼？",
		CACTUS_FLOWER = "花真是好看又好吃",

		COLDFIRE =
		{
			EMBERS = "我要放点东西进去",
			GENERIC = "蓝色？？？冰冷？？？",
			HIGH = "地狱之火！",
			LOW = "怎么办？快没了",
			NORMAL = "好吧，我不信科学",
			OUT = "前辈都怪你！不加柴火",
		},
		CAMPFIRE =
		{
			EMBERS = "木头不能吃，把它扔进去吧！",
			GENERIC = "黑夜里最亮的星",
			HIGH = "那个？！感觉不妙啊",
			LOW = "你要变成渣渣灰了吗？",
			NORMAL = "快快，烤食物！",
			OUT = "你吼，渣渣灰",
		},
		CANE = "我不明白为什么可以走得快一点",
		CATCOON = "哈哈，好有趣，好可爱",
		CATCOONDEN = 
		{
			GENERIC = "洞里有什么啊？",
			EMPTY = "前辈快去里面看看有什么！",
		},
		CATCOONHAT = "学雷锋，好榜样",
		COONTAIL = "这个不会腐败吗？",
		CARROT = "哈哈，兔子最爱，都是我的最爱",
		CARROT_COOKED = "是谁切的片？",
		CARROT_PLANTED = "嗯?发现了！",
		CARROT_SEEDS = "这个估计是最差劲的了",
		WATERMELON_SEEDS = "吃西瓜，吃西瓜！",
		CAVE_FERN = "蕨类也是可以吃的！",
		CHARCOAL = "木头先生的遗物",
        CHESSJUNK1 = "真是浪费背包",
        CHESSJUNK2 = "真是浪费背包",
        CHESSJUNK3 = "真是浪费背包",
		CHESTER = "哦哦哦！可爱！我不会吃你的",
		CHESTER_EYEBONE =
		{
			GENERIC = "哦，前辈，它在盯着你",
			WAITING = "有一瞬间我觉得它是要么恩",
		},
		COOKEDMANDRAKE = "前辈，不忍心吃它怎么办？",
		COOKEDMEAT = "这简直是犯罪！",
		COOKEDMONSTERMEAT = "感觉好多了，毕竟还是肉啊",
		COOKEDSMALLMEAT = "感觉小肉要一锅煮才够吃啊",
		COOKPOT =
		{
			COOKING_LONG = "快点啊，不然把你也吃了",
			COOKING_SHORT = "还差一点点！",
			DONE = "哇哇哇！前辈，做好了！",
			EMPTY = "嗯？我应该放点东西进去的",
			BURNT = "本是同根生，相煎何太急",
		},
		CORN = "前辈！玉米！",
		CORN_COOKED = "哇哦！爆米花！",
		CORN_SEEDS = "不应该是一粒玉米吗？",
		CROW =
		{
			GENERIC = "邪恶！",
			HELD = "被我掌控了！",
		},
		CUTGRASS = "为什么我不是牛或是羊？",
		CUTREEDS = "感觉会很需要它！",
		CUTSTONE = "光滑无比",
		DEADLYFEAST = "前辈说这个不能吃的，但是好诱人啊！",
		DEERCLOPS = "前辈快跑！！！",
		DEERCLOPS_EYEBALL = "呃~~~这不是妖梦的？",
		EYEBRELLAHAT =	"扶摇直上九万里！",
		DEPLETED_GRASS =
		{
			GENERIC = "秃了！？",
		},
		DEVTOOL = "是我的错觉吗，闻起来好香",
		DEVTOOL_NODEV = "我要挥动它",
		DIRTPILE = "前辈，那是一堆什么？",
		DIVININGROD =
		{
			COLD = "很远~~~很远",
			GENERIC = "也是一个指南针？",
			HOT = "简直发狂了",
			WARM = "快！前辈，朝着这边！",
			WARMER = "哦哦！快点，快到了",
		},
		DIVININGRODBASE =
		{
			GENERIC = "这是？有个洞？",
			READY = "看样子要一个大钥匙",
			UNLOCKED = "开始工作咯！",
		},
		DIVININGRODSTART = "前辈，我干的漂亮吗？",
		DRAGONFLY = "飞翔的烤肉？",
		ARMORDRAGONFLY = "Hot mail!",
		DRAGON_SCALES = "好温暖啊！",
		DRAGONFLYCHEST = "烤...烤箱！",
		LAVASPIT = 
		{
			HOT = "口水也会着火？？？",
			COOL = "恶心恶心恶心！",
		},
		LAVA_POND = "前辈，洗个热水澡吧，哈哈哈！",
		LAVAE = "啊！好烫好烫！！！",
		LAVAE_PET = 
		{
			STARVING = "饿？我...我没有吃的，别看我",
			HUNGRY = "它肚子叫了，我也饿了",
			CONTENT = "哈哈，前辈它好像很开心",
			GENERIC = "我甚至忘了它是个怪物！",
		},
		LAVAE_EGG = 
		{
			GENERIC = "想吃，怎么办？",
		},
		LAVAE_EGG_CRACKED =
		{
			COLD = "看上去有点冷？烤了它吧，嘿嘿嘿",
			COMFY = "很开心嘛，越看越好吃",
		},
		LAVAE_TOOTH = "蛋有牙齿？",

		DRAGONFRUIT = "前辈，扒了它的皮！！呜哈哈哈~~~",
		DRAGONFRUIT_COOKED = "总感觉不是所有水果都可以这样处理",
		DRAGONFRUIT_SEEDS = "难道是火龙果里的小黑豆吗？",
		DRAGONPIE = "简直是盛宴",
		DRUMSTICK = "前辈，我...我...",
		DRUMSTICK_COOKED = "香飘十里！",
		DUG_BERRYBUSH = "看上去应该还有浆果的啊",
		DUG_GRASS = "草根？",
		DUG_MARSH_BUSH = "不太友好啊",
		DUG_SAPLING = "种在我家边上",
		DURIAN = "前辈，你先吃，我对你好吧！",
		DURIAN_COOKED = "更是香飘十里！！！",
		DURIAN_SEEDS = "危险的榴莲种子",
		EARMUFFSHAT = "那俩个兔子哪里去了？",
		EGGPLANT = "直接咬一口吧！",
		EGGPLANT_COOKED = "哟吼！有点烫手，有点烫胃",
		EGGPLANT_SEEDS = "茄子的种子长在哪？",
		DECIDUOUSTREE = 
		{
			BURNING = "这很凄惨，很壮观！",
			BURNT = "不好意思，你还活着吗？",
			CHOPPED = "光秃秃，有点难看啊",
			POISON = "啊咧，还会这样？",
			GENERIC = "绿了，黄了，秃了",
		},
		ACORN = 
		{
		    GENERIC = "里面的东西肯定能吃，吃货的自觉！",
		    PLANTED = "为什么种下去就发芽了",
		},
		ACORN_COOKED = "哈哈，我就知道一定能吃",
		BIRCHNUTDRAKE = "呜啊！它会咬人！",
		EVERGREEN =
		{
			BURNING = "这很凄惨，很壮观！",
			BURNT = "不好意思，你还活着吗？",
			CHOPPED = "光秃秃，有点难看啊",
			GENERIC = "一直都是绿油油",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "这很凄惨，很壮观！",
			BURNT = "不好意思，你还活着吗？",
			CHOPPED = "光秃秃，有点难看啊",
			GENERIC = "前辈，这个树好可怜啊",
		},
		EYEPLANT = "前...前辈！它在盯着我！",
		FARMPLOT =
		{
			GENERIC = "种，吃！",
			GROWING = "快点快点！",
			NEEDSFERTILIZER = "它好像没什么精神",
			BURNT = "怎么...怎么会这样？",
		},
		FEATHERHAT = "？！愤怒的小鸟！？",
		FEATHER_CROW = "邪恶的羽毛",
		FEATHER_ROBIN = "鲜红的，血？",
		FEATHER_ROBIN_WINTER = "白色，有点冷啊",
		FEM_PUPPET = "它再睡觉吗？",
		FIREFLIES =
		{
			GENERIC = "前辈，我想抓萤火虫",
			HELD = "哈哈，感觉我也在发光",
		},
		FIREHOUND = "红烧狗肉？",
		FIREPIT =
		{
			EMBERS = "加点燃料吧",
			GENERIC = "温暖又贴心",
			HIGH = "烧吧！烧吧！",
			LOW = "撑住啊",
			NORMAL = "温暖又贴心",
			OUT = "幸好可以重来",
		},
		COLDFIREPIT =
		{
			EMBERS = "还行不行啊",
			GENERIC = "认真你就输了",
			HIGH = "地狱之火！",
			LOW = "加木头？可以是冷火？",
			NORMAL = "不科学的东西，认真你就输了",
			OUT = "重新开始",
		},
		FIRESTAFF = "烧烤派对",
		FIRESUPPRESSOR = 
		{	
			ON = "为什么加燃料会喷冰？",
			OFF = "不动了？可以做冰激凌？",
			LOWFUEL = "它饿了吗？我是饿了",
		},

		FISH = "鱼鱼鱼，没刺最好了",
		FISHINGROD = "前辈，一起去钓鱼吧",
		FISHSTICKS = "将其整个吞下去！",
		FISH_MED = "里外都是鱼，狗在哪里？",
		FISH_MED_COOKED = "烤鱼...狗？",
		FISHTACOS = "它不会存在很久，因为有我",
		FISH_COOKED = "那根讨厌的刺",
		FLINT = "好锋利！",
		FLOWER = "我想试试味，看看好不好吃",
		FLOWERHAT = "嗯，真香！",
		FLOWER_EVIL = "基因突变？",
		FOLIAGE = "让我吃吃看！",
		FOOTBALLHAT = "忠实粉丝！",
		FROG =
		{
			DEAD = "它在叫？",
			GENERIC = "生命窃取？",
			SLEEPING = "睁开眼睛睡觉？",
		},
		FROGGLEBUNWICH = "汉堡不是应该有汉堡肉吗？",
		FROGLEGS = "感觉生命被掏空",
		FROGLEGS_COOKED = "吃起来像鸡肉，嘎嘣脆",
		FRUITMEDLEY = "我都流口水了",
		FURTUFT = "黑白毛", 
		GEARS = "做冰箱，放食物！",
		GHOST = "呜呜呜，我好怕！",
		GOLDENAXE = "年轻的樵夫哦！",
		GOLDENPICKAXE = "我掉的是金锄头！哈哈",
		GOLDENPITCHFORK = "金叉子？",
		GOLDENSHOVEL = "喜爱福？",
		GOLDNUGGET = "我要买盆栽！",
		GRASS =
		{
			BARREN = "金坷垃！",
			WITHERED = "小草。你也热吧",
			BURNING = "我的草在烈火中永生",
			GENERIC = "没有刀子啊，割草？",
			PICKED = "还剩一点呢",
		},
		GREEN_CAP = "绿帽子？",
		GREEN_CAP_COOKED = "熟了的绿帽子",
		GREEN_MUSHROOM =
		{
			GENERIC = "绿蘑菇有毒吗",
			INGROUND = "快出来，保证不吃你",
			PICKED = "根我也想挖了",
		},
		GUNPOWDER = "危险的东西",
		HAMBAT = "我想吃一下啊",
		HAMMER = "加个雷神就厉害了",
		HEALINGSALVE = "我的血有救了",
		HEATROCK =
		{
			FROZEN = "一块石头都结冰了",
			COLD = "还会变色？",
			GENERIC = "石头也疯狂",
			WARM = "还会变色？",
			HOT = "有点烫啊",
		},
		HOME = "我也想要啊",
		HOMESIGN = 
		{
			GENERIC = "这是我的家吗",
			UNWRITTEN = "什么都没有吗？",
			BURNT = "哦！又是火",
		},
		HONEY = "甜蜜蜜",
		HONEYCOMB = "这里面一定还有！",
		HONEYHAM = "嘿嘿...嘿嘿嘿...",
		HONEYNUGGETS = "蛋白质是牛肉的五倍",
		HORN = "肉快来！",
		HOUND = "就是移动的狗肉",
		HOUNDBONE = "肉呢？",
		HOUNDMOUND = "狗这么进去的？",
		ICEBOX = "食物的藏身所！",
		ICEHAT = "前辈你要试试吗",
		ICEHOUND = "冷冻的狗肉不好吃",
		INSANITYROCK =
		{
			ACTIVE = "不太稳定？",
			INACTIVE = "不太稳定？",
		},
		JAMMYPRESERVES = "前辈我还要吐司",
		KABOBS = "BBQ!",
		KILLERBEE =
		{
			GENERIC = "讨厌，可怕，快跑！",
			HELD = "你也有今天！",
		},
		KNIGHT = "将军！",
		KOALEFANT_SUMMER = "超...超级大肉块",
		KOALEFANT_WINTER = "简直就是肉堆",
		KRAMPUS = "你动下我的食物看看！",
		KRAMPUS_SACK = "欧气爆表",
		LEIF = "哦哦哦！它会动",
		LEIF_SPARSE = "哦哦哦！它会动",
		LIGHTNING_ROD =
		{
			CHARGED = "这个电能可以利用吗！",
			GENERIC = "直指天空",
		},
		LIGHTNINGGOAT = 
		{
			GENERIC = "跳跳肉！",
			CHARGED = "雷电法王？",
		},
		LIGHTNINGGOATHORN = "上面不会有电吧？",
		GOATMILK = "完了，口水掉进去了",
		LITTLE_WALRUS = "人傻肉多",
		LIVINGLOG = "它不高兴？",
		LOCKEDWES = "你还好吧？",
		LOG =
		{
			BURNING = "好惨啊",
			GENERIC = "要致富先撸树",
		},
		LUREPLANT = "有点危险啊",
		LUREPLANTBULB = "种瓜得瓜种肉得肉",
		MALE_PUPPET = "男的？",
		MANDRAKE =
		{
			DEAD = "你死了吗？吃吃吃！",
			GENERIC = "这不是胡萝卜！",
			PICKED = "可爱又有点吵",
		},
		MANDRAKESOUP = "前辈，这个会不会有点苦",
		MANDRAKE_COOKED = "这次真死了",
		MARBLE = "怎么只剩下一个角了",
		MARBLEPILLAR = "拆拆拆！",
		MARBLETREE = "它会生长吗？",
		MARSH_BUSH =
		{
			BURNING = "烧的漂亮！",
			GENERIC = "前辈，你先上！",
			PICKED = "前辈，你先上！",
		},
		BURNT_MARSH_BUSH = "前辈，你帮我拿着吧",
		MARSH_PLANT = "能吃吗？",
		MARSH_TREE =
		{
			BURNING = "火焰吞噬",
			BURNT = "感觉瘦了不少",
			CHOPPED = "又没了",
			GENERIC = "又有刺？",
		},
		MAXWELL = "前辈他欺负我！",
		MAXWELLHEAD = "这不是一个头吗？",
		MAXWELLLIGHT = "为什么不会熄灭，为什么是黑的？",
		MAXWELLLOCK = "这怕不是个钥匙孔",
		MAXWELLTHRONE = "我认为可以走了",
		MEAT = "最原始的渴望！",
		MEATBALLS = "四喜丸子？",
		MEATRACK =
		{
			DONE = "咸鱼？？？",
			DRYING = "希望我不会提前吃了",
			DRYINGINRAIN = "下雨了，可以吃了？",
			GENERIC = "为什么不产咸鱼？",
			BURNT = "谁比较干呢？",
		},
		MEAT_DRIED = "我的口水又把它弄湿了",
		MERM = "看上去好傻！哈哈哈",
		MERMHEAD = 
		{
			GENERIC = "恶臭无比",
			BURNT = "烤鱼头？",
		},
		MERMHOUSE = 
		{
			GENERIC = "难道不会进水？",
			BURNT = "烤鱼的香气！",
		},
		MINERHAT = "虫子在里面没事吧？",
		MONKEY = "好烦！",
		MONKEYBARREL = "古老的祭坛？",
		MONSTERLASAGNA = "失败的美味",
		FLOWERSALAD = "花花的美味",
        ICECREAM = "嘿嘿...嘿嘿...",
        WATERMELONICLE = "西瓜冰棒可以煮出来？？",
        TRAILMIX = "是大肉的脚印！",
        HOTCHILI = "辣死了！",
        GUACAMOLE = "鼹鼠不好吃吧！",
		MONSTERMEAT = "虽然是肉，但是我却没胃口",
		MONSTERMEAT_DRIED = "前辈，我是不是做了无用功啊",
		MOOSE = "吃了它的肉我会不会变傻",
		MOOSE_NESTING_GROUND = "巢有点小？",
		MOOSEEGG = "前辈我想直接煮了！",
		MOSSLING = "很傻，很可爱",
		FEATHERFAN = "火焰山在哪？",
		MINIFAN = "不错不错！",
		TROPICALFAN = "不错不错！",
		GOOSE_FEATHER = "有点臭！",
		STAFF_TORNADO = "风啊！！！",
		MOSQUITO =
		{
			GENERIC = "敢吸我的血？有勇气！",
			HELD = "你再吸啊！",
		},
		MOSQUITOSACK = "这可以装下我的血！",
		MOUND =
		{
			DUG = "就这么没了？",
			GENERIC = "前辈，欧气一波",
		},
		NIGHTLIGHT = "黑火？？？",
		NIGHTMAREFUEL = "这不是妖梦吗？",
		NIGHTSWORD = "拿着它我会做噩梦的",
		NITRE = "它应该也可以烧的",
		ONEMANBAND = "不如跳舞！",
		PANDORASCHEST = "这里面怕不是妖梦！",
		PANFLUTE = "前辈，想睡觉吗？",
		PAPYRUS = "只是纸而已",
		PENGUIN = "前辈，它们下鸡蛋！",
		PERD = "大吉大利，今晚吃鸡",
		PEROGIES = "尝起来不错",
		PETALS = "吃花，花痴！",
		PETALS_EVIL = "你也是被诅咒的吗？",
		PHLEGM = "噢~~~什么东西！",
		PICKAXE = "挖矿？",
		PIGGYBACK = "东西放在里面会不会臭啊",
		PIGHEAD = 
		{	
			GENERIC = "前辈，这是祭品吗",
			BURNT = "红烧猪头肉！",
		},
		PIGHOUSE =
		{
			FULL = "蛋白质你在里面吗？",
			GENERIC = "前辈，这是养猪场吗！",
			LIGHTSOUT = "快出来，蛋白质，我知道你在",
			BURNT = "哈哈，烤乳猪！",
		},
		PIGKING = "小猪佩奇身上纹，你我都是社会人",
		PIGMAN =
		{
			DEAD = "蛋白质你怎么了",
			FOLLOWER = "前辈，蛋白质在跟着我",
			GENERIC = "区区一坨蛋白质",
			GUARD = "厉害的蛋白质？",
			WEREPIG = "蛋白质变异了吗？不还是蛋白质！",
		},
		PIGSKIN = "上面有个小尾巴",
		PIGTENT = "培根？",
		PIGTORCH = "为什么我点不着它",
		PINECONE = 
		{
		    GENERIC = "其实松子也可以吃的",
		    PLANTED = "一瞬间叶子都有了",
		},
		LUMPY_SAPLING = "它怎么繁殖？",
		PITCHFORK = "闰土，迅哥儿！",
		PLANTMEAT = "这也是肉吧",
		PLANTMEAT_COOKED = "还是没什么胃口",
		PLANT_NORMAL =
		{
			GENERIC = "为什么都是这样的？",
			GROWING = "前辈，它长的好慢啊！",
			READY = "欧气满满哦！",
			WITHERED = "我讨厌夏天",
		},
		POMEGRANATE = "其实有点讨厌麻烦的水果",
		POMEGRANATE_COOKED = "里面还有核吗？",
		POMEGRANATE_SEEDS = "这个不能种出石榴吧",
		POND = "前辈，和我抓鱼吃！",
		POOP = "@#￥%&*&￥%......",
		FERTILIZER = "骨天乐你还好吗？",
		PUMPKIN = "南瓜果然要配万圣节！",
		PUMPKINCOOKIE = "我想象中的南瓜饼不是这样的",
		PUMPKIN_COOKED = "前辈，抹饼吃！",
		PUMPKIN_LANTERN = " 呜~嘶~嗷~",
		PUMPKIN_SEEDS = "终于有点像南瓜种子了",
		PURPLEAMULET = "妖梦乐园？？？",
		PURPLEGEM = "能源紫水晶？",
		RABBIT =
		{
			GENERIC = "兔肉也不错吗",
			HELD = " 煎烤炸煮焖炒蒸！",
		},
		RABBITHOLE = 
		{
			GENERIC = "兔子生产器",
			SPRING = "春天不营业？",
		},
		RAINOMETER = 
		{	
			GENERIC = "前辈，会下雨了吗？",
			BURNT = "烈火！净化！",
		},
		RAINCOAT = "前辈你也穿上吧",
		RAINHAT = "前辈，你看我...",
		RATATOUILLE = "珍珠翡翠白玉汤！",
		RAZOR = "我没有胡子啊！",
		REDGEM = "里面似乎有火苗",
		RED_CAP = "其实不好吃",
		RED_CAP_COOKED = "依然不好吃！",
		RED_MUSHROOM =
		{
			GENERIC = "前辈，我想吃一下试试",
			INGROUND = "啊咧，快出来呀！",
			PICKED = "现在我没办法了",
		},
		REEDS =
		{
			BURNING = "它烧起啦！",
			GENERIC = "芦苇长这样？",
			PICKED = "不是还有一点点吗",
		},
        RELIC = 
        {
            GENERIC = "在很久很久以前...",
            BROKEN = "它好像坏了",
        },
        RUINS_RUBBLE = "应该可以修的",
        RUBBLE = "石头堆！",
		RESEARCHLAB = 
		{	
			GENERIC = "好像一个稻草人！",
			BURNT = "稻草人果然怕火",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "前辈，这是稻草人的哥哥吗？",
			BURNT = "为什么它也可以燃烧？",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "兔子去哪了？",
			BURNT = "里面会不会有烤兔肉？",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "这估计是最厉害的了",
			BURNT = "它不会用魔法保护自己吗？",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "我的肉就做出这样的东西？哼！",
			BURNT = "里面还有肉吗？",
		},
		RESURRECTIONSTONE = "一个神奇的祭坛",
		ROBIN =
		{
			GENERIC = "看起来我要尝尝",
			HELD = "前辈，它摸起来好舒服！",
		},
		ROBIN_WINTER =
		{
			GENERIC = "它冷吗？我来班它烤烤！",
			HELD = "果然还是烧烤",
		},
		ROBOT_PUPPET = "这是什么？",
		ROCK_LIGHT =
		{
			GENERIC = "这是石头？？",
			OUT = "没有了？",
			LOW = "快完了",
			NORMAL = "可以烤东西吗？",
		},
		ROCK = "看起来像馒头",
		ROCK_ICE = 
		{
			GENERIC = "好大的冰淇淋！",
			MELTED = "冰淇淋你瘦了！",
		},
		ROCK_ICE_MELTED = "前辈，它会回来吗？",
		ICE = "快尝尝！好冰！",
		ROCKS = "看起来像馒头",
        ROOK = "哇，前辈，它冲过来了！！",
		ROPE = "它并没有想象中那么长吧",
		ROTTENEGG = "呜呜呜！前辈，吃不了了！",
		SANITYROCK =
		{
			ACTIVE = "简直疯狂",
			INACTIVE = "总算安静了",
		},
		SAPLING =
		{
			BURNING = "火带走了一切",
			WITHERED = "它和我一样热",
			GENERIC = "小树苗，好可爱",
			PICKED = "被榨干了",
		},
		SEEDS = "谜一样的东西",
		SEEDS_COOKED = "这个是米饭吗？",
		SEWING_KIT = "前辈看我心灵手巧！",
		SHOVEL = "喜爱福？",
		SILK = "这个这么那么完整？",
		SKELETON = "哇！！！前辈，那是什么？好害怕！",
		SCORCHED_SKELETON = "哇！！！前辈！好害怕！还烧焦了！",
		SKELETON_PLAYER = "哇！！！前辈！它不会动吧？",
		SKULLCHEST = "前辈，还是你去吧",
		SMALLBIRD =
		{
			GENERIC = "哦哦！好可爱！",
			HUNGRY = "看它饿我也饿了",
			STARVING = "喂？喂！怎么会这样？",
		},
		SMALLMEAT = "唉！不如大肉过瘾",
		SMALLMEAT_DRIED = "刚好一口一个",
		SPAT = "前辈，和你一样顽固",
		SPEAR = "为什么不用我的刀？",
		SPIDER =
		{
			DEAD = "去死去死去死！！！",
			GENERIC = "一块灵活的怪兽肉",
			SLEEPING = "感觉也没那么可怕！",
		},
		SPIDERDEN = "啊！前辈，好粘啊",
		SPIDEREGGSACK = "这个可以带着走吗？",
		SPIDERGLAND = "有毒吧！大概",
		SPIDERHAT = "好丑的帽子！",
		SPIDERQUEEN = "啊啊啊！超大怪兽肉",
		SPIDER_WARRIOR =
		{
			DEAD = "终于干掉你了",
			GENERIC = "一块难缠的怪兽肉",
			SLEEPING = "趁现在！！！",
		},
		SPOILED_FOOD = "哦！上面都有毛了！",
		STATUEHARP = "它的头去哪里？",
		STATUEMAXWELL = "有这么高吗？",
		STEELWOOL = "用来洗碗？？？",
		STINGER = "前辈，小心点，别被扎到了",
		STRAWHAT = "面朝黄土背朝天",

		TALLBIRD = "长腿！独眼？？？妖梦！！！",
		TALLBIRDEGG = "嗯！煎蛋配烤肉",
		TALLBIRDEGG_COOKED = "前辈，烤肉好了吗？",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "你冷吗，我肚子里暖和！",
			GENERIC = "看上去还是美味",
			HOT = "看上去快熟了，真香",
			LONG = "好慢啊~~~",
			SHORT = "马上就是吃肉了，而不是蛋",
		},
		TALLBIRDNEST =
		{
			GENERIC = "好小，好小",
			PICKED = "啊咧？没有蛋吗？",
		},
		TEENBIRD =
		{
			GENERIC = "年轻的力量！！！",
			HUNGRY = "它怎么又饿了！",
			STARVING = "啊啊啊！前辈，它好像快不行了",
		},
		TELEBASE =
		{
			VALID = "准备出发！",
			GEMS = "简直是宝石吞噬者",
		},
		GEMSOCKET = 
		{
			VALID = "完成！",
			GEMS = "你这贪吃的家伙",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "穿越时空！！！",
			GENERIC = "那一边会有什么？",
			LOCKED = "好像有什么不见了！",
			PARTIAL = "没事就快完成了",
		},
		TELEPORTATO_BOX = "没用的东西！又不能吃",
		TELEPORTATO_CRANK = "没用的东西！又不能吃",
		TELEPORTATO_POTATO = "没用的东西！又不能吃",
		TELEPORTATO_RING = "没用的东西！又不能吃",
		TELESTAFF = "前辈又来玩捉迷藏吧！",
		TENT = 
		{
			GENERIC = "前辈，我想睡在床上！",
			BURNT = "幸好我出来了",
		},
		SIESTAHUT = 
		{
			GENERIC = "避暑胜地！",
			BURNT = "里面比外面还热！",
		},
		TENTACLE = "好恶心啊！~啊！啊!",
		TENTACLESPIKE = "这个是从它身上掉下来的吗？好假",
		TENTACLESPOTS = "这个皮上全是粘液！",
		TENTACLE_PILLAR = "哦啊！~~全是粘液！",
		TENTACLE_PILLAR_HOLE = "前...前辈，你...你下去看看吧！",
		TENTACLE_PILLAR_ARM = "哇！居然会动！",
		TENTACLE_GARDEN = "Yet another slimy pole.",
		TOPHAT = "这个帽子不是白色的吗？谁染的色？",
		TORCH = "这个应该也可以用来烧烤的！",
		TRANSISTOR = "高科技？",
		TRAP = "去抓小肉！",
		TRAP_TEETH = "它会不会误伤啊！",
		TRAP_TEETH_MAXWELL = "前辈，你去试试吧，感觉不妙",
		TREASURECHEST = 
		{
			GENERIC = "哦！是箱子吗？",
			BURNT = "烈火吞噬！",
		},
		TREASURECHEST_TRAP = "前辈，去试试吧！嘿嘿嘿~~~",
		TREECLUMP = "这么感觉周围会全是这个！",

		TRINKET_1 = "养猪场老大的流通货币",
		TRINKET_10 = "养猪场老大的流通货币",
		TRINKET_11 = "养猪场老大的流通货币",
		TRINKET_12 = "养猪场老大的流通货币",
		TRINKET_2 = "养猪场老大的流通货币",
		TRINKET_23 = "养猪场老大的流通货币",
		TRINKET_3 = "养猪场老大的流通货币",
		TRINKET_4 = "养猪场老大的流通货币",
		TRINKET_5 = "养猪场老大的流通货币",
		TRINKET_6 = "养猪场老大的流通货币",
		TRINKET_7 = "养猪场老大的流通货币",
		TRINKET_8 = "养猪场老大的流通货币",
		TRINKET_9 = "养猪场老大的流通货币",

		BISHOP_CHARGE_HIT = "啊！呜呜呜~~前辈它欺负我",
		TRUNKVEST_SUMMER = "和它兄弟比起来差远了",
		TRUNKVEST_WINTER = "和它兄弟比起来强多了",
		TRUNK_COOKED = "其实不想吃这种奇奇怪怪的肉",
		TRUNK_SUMMER = "鼻子是直接割下来的？好可怕",
		TRUNK_WINTER = "鼻子是直接割下来的？好可怕",
		TUMBLEWEED = "前辈今天也要欧气满满哦！",
		TURF_DIRT = "一块草皮而已",
		TURF_FOREST = "一块草皮而已",
		TURF_GRASS = "一块草皮而已",
		TURF_MARSH = "一块草皮而已",
		TURF_ROAD = "一块草皮而已",
		TURF_ROCKY = "一块草皮而已",
		TURF_SAVANNA = "一块草皮而已",
		TURKEYDINNER = "感恩节？感谢！哦耶！！！",
		TWIGS = "用来烧烤吧",
		UMBRELLA = "前辈，一起打伞吧！",
		GRASS_UMBRELLA = "前辈，一起打伞吧！",
		PALMLEAF_UMBRELLA = "前辈，一起打伞吧！",
		UNIMPLEMENTED = "呃~~前辈，快去看看！",
		WAFFLES = "呜哇！！！前辈你有糖吗？",
		WALL_HAY = 
		{	
			GENERIC = "只是墙而已",
			BURNT = "火烧连营！",
		},
		WALL_HAY_ITEM = "只是墙而已",
		WALL_STONE = "只是墙而已",
		WALL_STONE_ITEM = "只是墙而已",
		WALL_RUINS = "只是墙而已",
		WALL_RUINS_ITEM = "只是墙而已",
		WALL_WOOD = 
		{
			GENERIC = "只是墙而已",
			BURNT = "火烧连营！",
		},
		WALL_WOOD_ITEM = "只是墙而已",
		WALL_MOONROCK = "只是墙而已",
		WALL_MOONROCK_ITEM = "只是墙而已",
		MOONROCKNUGGET = "哇！前辈，好漂亮的石头！",
		ROCK_MOON = "这个石头会不会是月亮上的？",
		WALRUS = "前辈，别让它跑了！",
		WALRUSHAT = "前辈，看我有没有艺术气息？",
		WALRUS_CAMP =
		{
			EMPTY = "喂！有人吗？没有？",
			GENERIC = "前辈，说话小声点！里面有人！",
		},
		WALRUS_TUSK = "哦哦哦，换钱！盆栽！",
		WARG = "我的肉城堡怎么是这样的？",
		WASPHIVE = "里面全是不友好！",
		WATERMELON = "大西瓜！哇哇哇！",
		WATERMELON_COOKED = "哦耶~~~",
		WATERMELONHAT = "我怕我会一口吃了去的",
		WETGOOP = "看上去好难吃啊！",
		WHIP = "有点吵啊！",
		WINTERHAT = "冬天的忠实伴侣！",
		WINTEROMETER = 
		{
			GENERIC = "四季如春？秋天更好吧！",
			BURNT = "是它控制不住下天吗？",
		},
		WORMHOLE =
		{
			GENERIC = "前辈，它会不会抢我的肉啊？",
			OPEN = "会不会很疼啊？",
		},
		WORMHOLE_LIMITED = "最讨厌一次性了",
		ACCOMPLISHMENT_SHRINE = "害怕（栗山未来饥荒限定版）",        
		LIVINGTREE = "千年树精？",
		ICESTAFF = "可以快速冷冻食物吗？",
		
        FLOTSAM = "前辈必须想点办法呀！",

        SUNKEN_BOAT = 
        {
            GENERIC = "前辈，它好像要说话耶！",
            ABANDONED = "哦！好可怜",
        },
        SUNKEN_BOAT_BURNT = "为什么烧的起来？",
   		SUNKEN_BOAT_TRINKET_1 = "只是垃圾而已", --sextant
		SUNKEN_BOAT_TRINKET_2 = "只是垃圾而已", --toy boat
		SUNKEN_BOAT_TRINKET_3 = "只是垃圾而已", --candle
		SUNKEN_BOAT_TRINKET_4 = "只是垃圾而已", --sea worther
		SUNKEN_BOAT_TRINKET_5 = "只是垃圾而已", --boot

		HOUNDFIRE = "啊！！！，怎么办怎么办？？？",

		--- CAPY DLC ------------------------------------------------------------------------------------------------

		STUFFEDEGGPLANT = "现已加入豪华午餐",
		SUNKBOAT = "感觉不行啊！",
		BANANAPOP = "虽然美味，但是好少啊！",
		BISQUE = "嗯，浓汤要配烤肉！",
		CEVICHE = "这酸爽，不敢相信！",
		SEAFOODGUMBO = "为什么里面有骨头？",
		SURFNTURF = "我似乎可以尝到很多美味！",
		SHARKFINSOUP = "好奢侈！！！",
		LOBSTERDINNER = "前辈，快来！麻辣小龙虾！",
		LOBSTERBISQUE = "哦，前辈，小龙虾被煮了！",
		JELLYOPOP = "话说水母可以做果冻？？？",
		SWEATERVEST = "不如我的衣服好看",
		REFLECTIVEVEST = "这不是消防员穿的吗？",
		HAWAIIANSHIRT = "前辈，看看我，感觉怎么样？",
		TAFFY = "好甜啊，前辈你也来一块！",

		ANTIVENOM = "这怕不是以毒攻毒？",
		VENOMGLAND = "罪恶之源",
		BLOWDART_POISON = "阴险的手法",
		OBSIDIANMACHETE = "前辈，它变得又黑又硬了！",
		SPEARGUN_POISON = "这玩意有毒！",
		OBSIDIANSPEARGUN = "好浪费啊！",
		LUGGAGECHEST = "前辈，欧气满满！",
		PIRATIHATITATOR =
		{
			GENERIC = "这个和之前的不一样啊",
			BURNT = "总感觉，火处于劣势",
		},
		COFFEEBEANS = "前辈，这个吃太多会醉吗？",
		COFFEE = "元气饮料",
		COFFEEBEANS_COOKED = "嗯~~~咖啡的香气",
		COFFEEBUSH =
		{
			BARREN = "这个鬼地方泯灭了它",
			WITHERED = "原来它也要施肥",
			GENERIC = "希望我不会太依赖它",
			PICKED = "还有多久啊！前辈！",
		},
		COFFEEBOT = "咖啡机？",
		MUSSEL = "有没有珍珠啊？",
		MUSSEL_FARM =
		{
			 GENERIC = "这是蛤蚌吗？",
			 STICKPLANTED = "饥荒有吸蛤"
		},

		MUSSEL_STICK = "吸蛤装备",
		LOBSTER = "哦哦哦！前辈快抓住它！！！我想吃小龙虾！",
		LOBSTERHOLE = "小家伙快出来！你和辣椒很配哦！",
		SEATRAP = "前辈，来和我一起等等...",
		SAND_CASTLE =
		{
			SAND = "哈哈！沙雕！！！",
			GENERIC = "沙雕！！！笑哭！"
		},
		BOATREPAIRKIT = "难道需要胶水！",

		BALLPHIN = "超级可爱！呃~前辈你在听吗？",
		BOATCANNON = "喔哄哄哄！我要征服海洋",
		BOTTLELANTERN = "这不是隔绝空气了吗？？？",
		BURIEDTREASURE = "欧气欧气！！！",
		BUSH_VINE =
		{
			BURNING = "它好像发火了",
			BURNT = "发火之后受伤的是自己",
			CHOPPED = "藤蔓回收！",
			GENERIC = "系兄弟就来砍我",
		},
		CAPTAINHAT = "前辈，快看，我像船长吗？",
		COCONADE =
		{
			BURNING = "开火！！！",
			GENERIC = "前辈！我XX的椰子炮呢？",
		},
		CORAL = "这是很多死去的小动物",
		CORALREEF = "冰山一角？",
		CRABHOLE = "这个进水了怎么办？",
		CUTLASS = "统治大海！",
		DUBLOON = "约等于盆栽！！！",
		FABRIC = "果然丝绸是最强的！！！",
		FISHINHOLE = "真是漂亮的鱼，在肚子里也是！",
		GOLDENMACHETE = "哇！金色传说！！！",
		JELLYFISH = "现在它会不会电我？",
		JELLYFISH_DEAD = "摸起来果冻一样，一定很好吃",
		JELLYFISH_COOKED = "洋葱圈？？？",
		JELLYFISH_PLANTED = "前辈，它似乎很友好？",
		JELLYJERKY = "果冻失去了它的信仰",

		LIMPETROCK =
		{
			GENERIC = "前辈，上有什么？？？",
			PICKED = "其实收之前还蛮恶心的",
		},
		LOGRAFT = "小船装载大梦想！",
		MACHETE = "菜鸟短剑？",
		MESSAGEBOTTLEEMPTY = "没有了！",
		MOSQUITO_POISON = "狠毒的怪物",
		OBSIDIANCOCONADE = "看起来更厉害了",
		OBSIDIANFIREPIT =
		{
			EMBERS = "我感觉要加点柴火！",
			GENERIC = "黑暗锅炉",
			HIGH = "纸是包不住火的！",
			LOW = "前辈，火小了很多",
			NORMAL = "最适合烤披萨！",
			OUT = "再来一次",
		},
		OX = "嗯哼？牛排？",
		PIRATEHAT = "钩子手和木头腿？",
		RAFT = "很安全？",
		ROWBOAT = "快速快速！",
		SAIL = "随风而动",
		SANDBAG_ITEM = "这个要怎么防水？",
		SANDBAG = "感觉很安心",
		SEASACK = "美食的家园",
		SEASHELL_BEACHED = "前辈看呀！是贝壳！",
		SEAWEED = "我并不认为海带炖汤很补",

		SEAWEED_PLANTED = "海带会浮在水面上？",
		SLOTMACHINE = "前辈，SSR！！！",
		SNAKE_POISON = "毒辣！",
		SNAKESKIN = "这个不应该入药吗？",
		SNAKESKINHAT = "李时珍皮",
		SOLOFISH = "不应该凶猛一点吗？",
		SPEARGUN = "为什么不能连发？",
		SPOILED_FISH = "散发一股恶臭！",
		SWORDFISH = "前辈，剑鱼好吃吗？",
		TRIDENT = "蕴藏着深海的魔法",
		TRINKET_13 = "只是垃圾而已",
		TRINKET_14 = "只是垃圾而已",
		TRINKET_15 = "只是垃圾而已",
		TRINKET_16 = "只是垃圾而已",
		TRINKET_17 = "只是垃圾而已",
		TRINKET_18 = "只是垃圾而已",
		TRINKET_19 = "只是垃圾而已",
		TURBINE_BLADES = "掀起一场龙卷风！",
		TURF_BEACH = "地皮而已",
		TURF_JUNGLE = "地皮而已",
		VOLCANO_ALTAR =
		{
			GENERIC = "前辈，好像是关闭的",
			OPEN = "前辈，打开了！",
		},
		VOLCANO_ALTAR_BROKEN = "呃~~~会不会出问题啊",
		WHALE_BLUE = "化而为鸟",
		WHALE_CARCASS_BLUE = "哦，开始发白了",
		WHALE_CARCASS_WHITE = "前辈，还是你来吧，好恶心",

		ARMOR_SNAKESKIN = "真皮沙发",
		CLOTHSAIL = "这个会不会不太结实？",
		DUG_COFFEEBUSH = "话说咖啡树是这个样子？",
		LAVAPOOL = "前辈，想不想洗个热水澡？",
		BAMBOO = "前辈，会有熊猫吗？",
		AERODYNAMICHAT = "奥特曼？",
		POISONHOLE = "最讨厌，没有之一",
		BOAT_LANTERN = "果然还是火把更帅！",
		DEAD_SWORDFISH = "感觉可以尝尝看",
		LIMPETS = "看起来不是吃的吧",
		OBSIDIANAXE = "战神斧！",
		COCONUT = 
		{
		    GENERIC = "它居然会偷袭我！",
		    PLANTED = "这个坚硬的外壳限制了它的能力",
		},
		COCONUT_COOKED = "前辈，一个蛋糕，谢谢！",
		BERMUDATRIANGLE = "哦！扭曲时空的力量",
		SNAKE = "蛇肉也是很香的嘛",
		SNAKEOIL = "蛇为什么有油？",
		ARMORSEASHELL = "铠甲勇士？",
		SNAKE_FIRE = "蛇着火了？",
		MUSSEL_COOKED = "要放点盐的",

		PACKIM_FISHBONE = "变身器？好厉害！",
		PACKIM = "为什么它会被骨头吸引？",

		ARMORLIMESTONE = "有酸就完蛋了",
		TIGERSHARK = "鱼，好大的鱼",
		WOODLEGS_KEY1 = "钥匙？用来干嘛？",
		WOODLEGS_KEY2 = "钥匙？用来干嘛？",
		WOODLEGS_KEY3 = "钥匙？用来干嘛？",
		WOODLEGS_CAGE = "它为什么不钻出来，那么大的洞",
		OBSIDIAN_WORKBENCH = "远古的工匠精神",

		NEEDLESPEAR = "这也是武器吗？",
		LIMESTONE = "前辈，稀盐酸！",
		DRAGOON = "最难看的龙",

		ICEMAKER = 
		{
			OUT = "它也会饿？",
			VERYLOW = "它好像撑不住了",
			LOW = "没精神？",
			NORMAL = "为什么可以造冰？",
			HIGH = "为什么可以造冰？",
		},

		DUG_BAMBOOTREE = "这样种也会活？",
		BAMBOOTREE =
		{
			BURNING = "根据物理学，此处应有爆鸣声",
			BURNT = "啊咧？没有爆鸣声？",
			CHOPPED = "竹子砍成这样还会活？",
			GENERIC = "有点矮",
		},
		JUNGLETREE =
		{
			BURNING = "烧吧！",
			BURNT = "芦柴棒？",
			CHOPPED = "又是一个灵魂",
			GENERIC = "前辈，这棵树不妙啊",
		},
		SHARK_GILLS = "鲨鱼肺？",
		TREEGUARD = "它也不愉快！",
		OBSIDIAN = "一块非常硬的石头",
		BABYOX = "全身都是肉！！！",
		STUNGRAY = "前辈，它怎么会飞啊？",
		SHARK_FIN = "奢侈的美味",
		FROG_POISON = "这长者有毒！",
		ARMOUREDBOAT = "海水很酸怎么办",
		ARMOROBSIDIAN = "铠甲合体",
		BIOLUMINESCENCE = "真是美景",
		SPEAR_POISON = "以眼还眼以牙还牙",
		SPEAR_OBSIDIAN = "刺穿敌人的心脏",
		SNAKEDEN =
		{
			BURNING = "碳烤蛇肉！真香",
			BURNT = "烧的好啊，好啊！",
			CHOPPED = "或许里面不会再有了吧",
			GENERIC = "前辈，不妙啊！",
		},
		TOUCAN = "嘴巴好大呀",
		MESSAGEBOTTLE = "里面似乎藏这宝藏的秘密",
		SAND = "随处可见",
		SANDHILL = "最好离我的鞋子远点",
		PEACOCK = "小偷？",
		VINE = "这个藤好短",
		SUPERTELESCOPE = "我眼睛更大了！",
		SEAGULL = "为什么海鸥黑色的？",
		SEAGULL_WATER = "为什么海鸥黑色的？",
		PARROT = "嗯？不掉金币？",
		ARMOR_LIFEJACKET = "我感觉穿上这个会看起来很胖！",
		WHALE_BUBBLES = "前辈，下面好像有什么东西？",
		EARRING = "我有戒指已经足够了",
		ARMOR_WINDBREAKER = "独自在风中凌乱",
		SEAWEED_COOKED = "有点咸，有点脆",
		CARGOBOAT = "其实并不能装很多东西",
		GASHAT = "净化我的肺",
		ELEPHANTCACTUS = "前辈，好大的仙人掌啊！",
		DUG_ELEPHANTCACTUS = "但愿放在口袋里不会扎我",
		ELEPHANTCACTUS_ACTIVE = "前辈，快跑，危险！",
		ELEPHANTCACTUS_STUMP = "它的利爪被磨平了",
		FEATHERSAIL = "孔雀开屏！",
		WALL_LIMESTONE_ITEM = "下酸雨怎么办？",
		JUNGLETREESEED =
        {
            GENERIC = "我觉得里面有小蛇",
            PLANTED = "这样做划不来呀",
        },
		VOLCANO = "未知的深渊",
		IRONWIND = "风驰电掣！",
		SEAWEED_DRIED = "好咸啊！！！",
		TELESCOPE = "我的眼睛变大了！",
		
		DOYDOY = "嘿！傻鸟！",
		DOYDOYBABY = "小可爱！",
		DOYDOYEGG = "嗯？新品种？赶快尝尝",
		DOYDOYEGG_CRACKED = "快要出来了？",
		DOYDOYFEATHER = "这不是孔雀的羽毛吗？",

		PALMTREE =
		{
			BURNING = "不知道有没有烤椰子",
			BURNT = "呃~~~~",
			CHOPPED = "椰子，嘿嘿嘿",
			GENERIC = "前辈我要椰子！",
		},
		PALMLEAF = "这个叶子好大啊",
		CHIMINEA = "让暴风雨来得更猛烈些吧！",
		DOUBLE_UMBRELLAHAT = "为什么要有两层？",
		CRAB = 
		{
			GENERIC = "别以为你穿了马甲我就不认识你了",
			HIDDEN = "又去换衣服？",
		},
		TRAWLNET = "抓鱼！！！",
		TRAWLNETDROPPED = 
		{
			SOON = "有鱼吗？",
			SOONISH = "这个怎么了？",
			GENERIC = "不会装不下了吧",
		},
		VOLCANO_EXIT = "话说这怎么出的去啊",
		SHARX = "来吧，看看谁吃谁！",
		SEASHELL = "贝壳这么都是一个样子？",
		WHALE_BUBBLES = "噢，前辈，它在冒泡",
		MAGMAROCK = "真·挖矿",
		MAGMAROCK_GOLD = "真·挖宝矿",
		CORAL_BRAIN_ROCK = "呃~~~大脑？",
		CORAL_BRAIN = "我可不是僵尸",
		SHARKITTEN = "可爱的可怕",
		SHARKITTENSPAWNER = 
		{
			GENERIC = "巨大的呼吸",
			INACTIVE = "怎么不动了？",
		},
		LIVINGJUNGLETREE = "这个头发还是很厉害的",
		WALLYINTRO_DEBRIS = "帆船，翻船",
		MERMFISHER = "怎么跟其他的不一样啊",
        PRIMEAPE = "可恨的东西，偷吃果实",
        PRIMEAPEBARREL = "玩个球",
        REDBARREL = "最初",
        PORTAL_SHIPWRECKED = "前辈，这个坏了",
		MARSH_PLANT_TROPICAL = "这是什么？",
		TELEPORTATO_SW_POTATO = "土豆是这个样子吗？",
		PIKE_SKULL = "可怕！",
		PALMLEAF_HUT = "午休时间",
		FISH_RAW_SMALL_COOKED = "太少了，不够吃啊",
		LOBSTER_DEAD = "龙虾自挂东南枝",
		MERMHOUSE_FISHER = "比其他房子高级",
		WILDBORE = "蛋白质生气了！",
		PIRATEPACK = "欧气爆棚",
		TUNACAN = "居然还有罐头",
		MOSQUITOSACK_YELLOW = "烦躁，讨厌",
		SANDBAGSMALL = "这个可以修战壕",
		FLUP = "快走开！！！",
		OCTOPUSKING = "很会偷懒",
		OCTOPUSCHEST = "无限箱子",
		GRASS_WATER = "水草？？？",
		WILDBOREHOUSE = "蛋白质的家",
		FISH_RAW_SMALL = "小到可怜！",
		TURF_SWAMP = "只是地皮而已",
		FLAMEGEYSER = "为什么不是喷泉而是喷火？",
		KNIGHTBOAT = "真的是莫名其妙",
		MANGROVETREE_BURNT = "水里也可以烧？",
		TIDAL_PLANT = "一株植物罢了",
		WALL_LIMESTONE = "别被腐蚀了",
		FISH_RAW = "大鱼大肉！",
		LOBSTER_DEAD_COOKED = "前辈，有麻辣酱吗？",
		BLUBBERSUIT = "穿在身上好恶心",
		BLOWDART_FLUP = "这是什么？恐怖",
		TURF_MEADOW = "只是地皮而已",
		TURF_VOLCANO = "只是地皮而已",
		SWEET_POTATO = "这个只有两片叶子？",
		SWEET_POTATO_COOKED = "切片？我想吃薯条！",
		SWEET_POTATO_PLANTED = "为什么种下去的时候不切片啊？",
		SWEET_POTATO_SEEDS = "亏大了，居然是土豆",
		BLUBBER = "一坨脂肪",
		TELEPORTATO_SW_RING = "垃圾玩意",
		TELEPORTATO_SW_BOX = "垃圾玩意",
		TELEPORTATO_SW_CRANK = "垃圾玩意",
		TELEPORTATO_SW_BASE = "垃圾玩意",
		VOLCANOSTAFF = "中二神器",
		THATCHPACK = "草包",
		TURF_DESERTDIRT = "只是地皮而已",
		SHARK_TEETHHAT = "这个不会扎头吗？",
		TURF_ASH = "只是地皮而已",
		TURF_FUNGUS_GREEN = "只是地皮而已",
		BOAT_TORCH = "我觉得如果是探照灯......",
		MANGROVETREE = "用水大户",
		HAIL_ICE = "前辈，我想吃沙冰",
		TROPICAL_FISH = "这个是咸水鱼还是淡水鱼？",
		TIDALPOOL = "要是温泉就好了",
		WHALE_WHITE = "开局一条鲲，装备全靠吞",
		VOLCANO_SHRUB = "你还好吗",
		ROCK_OBSIDIAN = "我的C4呢？",
		ROCK_CHARCOAL = "这个不是煤矿吗？为什么是木炭？",
		DRAGOONDEN = "透露出不友好",
		WILBUR_UNLOCK = "为王的诞生献上礼炮",
		WILBUR_CROWN = "罪恶王冠",
		TWISTER = "龙卷风摧毁停车场！",
		TWISTER_SEAL = "我觉得这是一个海豹腿，可以吃的",
		MAGIC_SEAL = "魔法，强大！",
		SAIL_STICK = "There must be a scientific explanation for this.",
		WIND_CONCH = "I can hear the wind trapped within.",
		DRAGOONEGG = "Do I hear cracking?",
		BUOY = "Awww yaaaaa buoy!", 
		TURF_SNAKESKINFLOOR = "只是地皮而已",
        DOYDOYNEST = "It's for doydoy eggs, dummy.",
		ARMORCACTUS = "The best defense is a good offense.",
		BRAINJELLYHAT = "Two brains means double the ideas!",
		COCONUT_HALVED = "When I click them together, they make horsey sounds.",
		CRATE = "There must be a way to open it.",
		DEPLETED_BAMBOOTREE = "Will it grow again?",
		DEPLETED_BUSH_VINE = "One day it may return.",
		DEPLETED_GRASS_WATER = "Farewell, sweet plant.",
		DOYDOYEGG_COOKED = "A controlled chemical reaction has made this egg matter more nutritious.",
		DRAGOONHEART = "Where the dragoon once stored its feelings.",
		DRAGOONSPIT = "It's SPITacularly disgusting!",
		DUG_BUSH_VINE = "I suppose I should pick it up.",
		FRESHFRUITCREPES = "Sugary fruit! Part of a balanced breakfast.",
		KRAKEN = "Now's not the time for me to be Quacken wise!",
		KRAKENCHEST = "To the victor, the spoils.",
		KRAKEN_TENTACLE = "A beast that never sleeps.",
		MAGMAROCK_FULL = "I can dig it.",
		MAGMAROCK_GOLD_FULL = "I see a golden opportunity.",
		MONKEYBALL = "I have a strange desire to name it after myself.",
		MONSTERTARTARE = "There's got to be something else to eat around here.",
		MUSSELBOUILLABAISE = "Imagine the experiments I could run on it!",
		MYSTERYMEAT = "I'm not dissecting that.",
		OXHAT = "Nice and dry. This helmet will protect me from the elements.",
		OX_FLUTE = "Is it dripping...?",
		OX_HORN = "I grabbed the ox by the horn.",
		PARROT_PIRATE = "I try not to eat anything with a name.",
		PEG_LEG = "I can perform amputations if anyone'd like to wear it for real.",
		PIRATEGHOST = "He met a terrible end. I will too if I don't get out of here.",
		SANDBAGSMALL_ITEM = "A bag full of sand. Does science know no bounds?",
		SHADOWSKITTISH_WATER = "Yikes!",
		SHIPWRECKED_ENTRANCE = "Ahoy!",
		SHIPWRECKED_EXIT = "And so, I sail away into the horizon!",
		SNAKESKINSAIL = "Scale it and sail it!",
		SPEAR_LAUNCHER = "Science takes care of me.",
		SWEETPOTATOSOUFFLE = "Sweet potato souffles are a rising trend.",
		SWIMMINGHORROR = "Yikes! Get me back to land!",
		TIGEREYE = "More eyes means better sight... right?",
		TRINKET_20 = "I'm not sure what it is, but it makes me feel smarter!",
		TRINKET_21 = "I ought to measure it to ensure it's to scale.",
		TRINKET_22 = "I'm sure someone would like this.",
		TURF_FUNGUS_RED = "只是地皮而已",
		TURF_MAGMAFIELD = "只是地皮而已",
		TURF_TIDALMARSH = "只是地皮而已",
		VOLCANO_ALTAR_TOWER = "How scary!",
		WATERYGRAVE = "Sure, I could fish it out of there. But should I?",
		WHALE_TRACK = "Whale, ho!",
		WILDBOREHEAD = "It smells as bad as it looks.",
		WOODLEGSBOAT = "A vessel fit for a scallywag.",
		WOODLEGSHAT = "Does it make me look scurvy... I mean scary!?",
		WOODLEGSSAIL = "The quintessential pirate sail.",
		WRECK = "Poor little boat.",
		INVENTORYGRAVE = "There was someone here before me!",
        INVENTORYMOUND = "There was someone here before me!",
		LIMPETS_COOKED = "Escargotcha!",
		RAWLING = "It's my buddy!",
		CALIFORNIAROLL = "But I don't have chopsticks.",

	--- 5C DLC ------------------------------------------------------------------------------------------------

        ENCRUSTEDBOAT = "A mere shell of a ship.",
        BABYOX = "哈哈，前辈，它好像在看着我",
        BALLPHINHOUSE = "The place where the ballphins roost.",
        DORSALFIN = "Guess that house is FINished.",
        NUBBIN = "I want nubbin to do with that.",
        CORALLARVE = "That's a baby coral reef.",
        RAINBOWJELLYFISH = "That's a lot of tendrils.",
        RAINBOWJELLYFISH_PLANTED = "A colorful blob of science.",
        RAINBOWJELLYFISH_DEAD = "An electric shock will not revive it. I tried.",
        RAINBOWJELLYFISH_COOKED = "A colorful snack!",
        RAINBOWJELLYJERKY = "All the water's dried right out of it.",
        WALL_ENFORCEDLIMESTONE = "I shelled out for the good stuff.",
        WALL_ENFORCEDLIMESTONE_ITEM = "I have to build it in the water.",
        CROCODOG = "I'd rather stay away from the business end of that jerk.",
        POISONCROCODOG = "That looks like an experiment gone wrong.",
        WATERCROCODOG = "It's a dog-eat-me world out here.",
        QUACKENBEAK = "I'd say I made the pecking order around here quite clear.",
        QUACKERINGRAM = "Does my ingenuity know no bounds?!",
    
    --- DLC ------------------------------------------------------------------------------------------------    

        CAVIAR = "I never had it before I came here.",
        CORMORANT = "I bet it eats a lot of fish.",

        FISH3 = "Surf and turf, hold the turf.",
        FISH4 = "This one's extra water repellent.",
        FISH5 = "It looks like a fish, but it feels clammy.",

        FISH3_COOKED = "That fish is fin-ished.",
        FISH4_COOKED = "Gilled to perfection.",
        FISH5_COOKED = "Fried fry.",

        FISH_FARM = 
        {
        	EMPTY = "I need to find some fish eggs for this.",
			STOCKED = "The fish babies haven't hatched yet.",
			ONEFISH = "There's a fish!",
			TWOFISH = "The fish are still multiplying.",
			REDFISH = "This has been a successful fish experiment!",
			BLUEFISH  = "I'd better start harvesting these!",
        },

        ROE = "Fish babies.",
        ROE_COOKED = "Roe, sunny side up.",
        
        SEA_YARD =
       	{
            ON = "For keeping my ships in tiptop shape!",
            OFF = "It's not in shipshape right now.",
            LOWFUEL = "I'll need to refill it soon.",
        },

        SEA_CHIMINEA = 
        {
            EMBERS = "Better put something on it before it goes out.",
            GENERIC = "Science protect my fires out here.",
            HIGH = "I'm glad we're surrounded by water.",
            LOW = "It's getting low.",
            NORMAL = "As cozy as it gets.",
            OUT = "It finally went out.",
        }, 

        TAR = "Do I have to hold it with my bare hands?",
        TAR_EXTRACTOR =
        {
            ON = "It's running smoothly.",
            OFF = "I have to turn it on.",
            LOWFUEL = "I need to refuel that.",
        },
        TAR_POOL = "There must be a way to get that tar out.",

        TARLAMP = "That's a real slick lamp.",
        TARSUIT = "I'll pitch a fit if I have to wear that.",
        TAR_TRAP = "Who's cleaning that up, I wonder?",

        TROPICALBOUILLABAISSE = "I seasoned it with a dash of science.",

        RESEARCHLAB5 = "For sea science!",
        WATERCHEST = "Watertight, just like all my theories.",
        QUACKENDRILL = "I can get more tar if I used this at sea.",
        HARPOON = "I don't intend to harp on the issue.",
        MUSSEL_BED = "I should find a good spot for these.",
	},

	DESCRIBE_GENERIC = "It's a... thing.",
	DESCRIBE_TOODARK = "It's too dark to see!",
	DESCRIBE_SMOLDERING = "That thing's about to catch fire.",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "Mmm. Beaky.",
	},
}
