STRINGS.NAMES.LIFESTONE = "Life stone"
STRINGS.RECIPE_DESC.LIFESTONE = "Plant a stone!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIFESTONE = "It can actually block the road!"

STRINGS.NAMES.YMSTONE = "YM Stone"
STRINGS.RECIPE_DESC.YMSTONE = "However,it doesn't change money"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.YMSTONE = "Prefect!Terrible!"

STRINGS.NAMES.CZYW = "Red dates pill"
STRINGS.RECIPE_DESC.CZYW = "Red dates replenish blood."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CZYW = "Well, why didn't I know that?"

STRINGS.NAMES.BLOODICEBOX = "Blood ice box"
STRINGS.RECIPE_DESC.BLOODICEBOX = "More powerful fresh preservation!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLOODICEBOX = "The producer is so lazy."

STRINGS.NAMES.LSWL_FLOWERPOT = "Potted plant"
STRINGS.RECIPE_DESC.LSWL_FLOWERPOT = "I lost all my nutrition to raise this things."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LSWL_FLOWERPOT = "What can I say......"

STRINGS.NAMES.BLOODSWORD = "Blood sword"
STRINGS.RECIPE_DESC.BLOODSWORD = "Favorite!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLOODSWORD = "Why attacks cost blood!"

STRINGS.NAMES.BLOODBLACKSWORD = "Black blood sword"
STRINGS.RECIPE_DESC.BLOODBLACKSWORD = "Hard-earned."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLOODBLACKSWORD = "Finally......"

STRINGS.NAMES.BLOODBLOWDART = "Blood blowdart"
STRINGS.RECIPE_DESC.BLOODBLOWDART = "Illogic!!!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLOODBLOWDART = "Wasting my blood!"

STRINGS.NAMES.GLASSES = "Glasses"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GLASSES = "The soul of glasses never dies!"

STRINGS.NAMES.LSWLSSCARF = "Scarf"
STRINGS.RECIPE_DESC.LSWLSSCARF = "Warm and sweet."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LSWLSSCARF = "I wish it was from the prefect."

STRINGS.NAMES.BLOODBAT = "Blood bat"
STRINGS.RECIPE_DESC.BLOODBAT = "Practical tool."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLOODBAT = "God's tool!"

STRINGS.NAMES.SEALRING = "Seal ring"
STRINGS.RECIPE_DESC.SEALRING = "Restore."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEALRING = "Sin!Power!"  

STRINGS.NAMES.BLOODBOOK = "Blood book"
STRINGS.RECIPE_DESC.BLOODBOOK = "Restore."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLOODBOOK = "It sucked my blood away."

STRINGS.NAMES.BLOODBOOK_REAP = "Blood book (Reap)"
STRINGS.RECIPE_DESC.BLOODBOOK_REAP = "Harvest time!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLOODBOOK_REAP = "Feel well!"

STRINGS.NAMES.BLOODBOOK_SUMMON = "Blood book (Summon) "
STRINGS.RECIPE_DESC.BLOODBOOK_SUMMON = "It's time to play."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLOODBOOK_SUMMON = "You can you up."

STRINGS.NAMES.BLOODBOOK_PLUS = "Blood book (plus)"
STRINGS.RECIPE_DESC.BLOODBOOK_PLUS = "More powerful effects."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLOODBOOK_PLUS = "It's just a book. It's so damn bad."

STRINGS.NAMES.EVILBLACKSTONE = "Evil stone"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.EVILBLACKSTONE = "I finally got it."

STRINGS.NAMES.THECURSEBLOOD = "Curse blood"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.THECURSEBLOOD = "This... This blood is toxic!"

STRINGS.NAMES.YM = "YM"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.YM = "Nurture passes nature."

STRINGS.NAMES.DEERCLOPSBLACK = "Shadow of nihility"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEERCLOPSBLACK = "Eh..........."

STRINGS.RECIPE_DESC.REDGEM = "Unscientific magic"
STRINGS.RECIPE_DESC.BLUEGEM = "Unscientific magic"

STRINGS.NAMES.YMQUINTESSENCE = "YM quintessence"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.YMQUINTESSENCE = "he necessary material for synthesizing YM Stone"

STRINGS.LSWL_INTRO_MAXWELL_1 = "What?!Who are you?"
STRINGS.LSWL_INTRO_MAXWELL_2 = "You have cursed blood on you!!"
STRINGS.LSWL_INTRO_MAXWELL_3 = "Get out of here!!!You're not welcome here!"

STRINGS.CHARACTER_TITLES.lswl = "Kuriyama Mirai "
STRINGS.CHARACTER_NAMES.lswl = "Kuriyama Mirai "
STRINGS.CHARACTER_DESCRIPTIONS.lswl = "*Special blood ability.\n*can improve unlock ability with curse power.\n*The sanity is very unstable, timid and afraid of the dark."
STRINGS.CHARACTER_QUOTES.lswl = "\"I'm not happy.\""

STRINGS.TABS.BLOODTAB = "Blood"