STRINGS.NAMES.LIFESTONE = "生命之石"
STRINGS.RECIPE_DESC.LIFESTONE = "种出石头"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIFESTONE = "其实它可以堵路"

STRINGS.NAMES.YMSTONE = "妖梦石"
STRINGS.RECIPE_DESC.YMSTONE = "让它成为军队吧"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.YMSTONE = "召唤我的小兵"

STRINGS.NAMES.CZYW = "吃早药丸"
STRINGS.RECIPE_DESC.CZYW = "zao  打不出来!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CZYW = "真的要完"

STRINGS.NAMES.BLOODICEBOX = "血箱"
STRINGS.RECIPE_DESC.BLOODICEBOX = "更给力的保鲜"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLOODICEBOX = "真偷懒"

STRINGS.NAMES.LSWL_FLOWERPOT = "盆栽"
STRINGS.RECIPE_DESC.LSWL_FLOWERPOT = "沾花惹草"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LSWL_FLOWERPOT = "..."

STRINGS.NAMES.BLOODSWORD = "血刃"
STRINGS.RECIPE_DESC.BLOODSWORD = "未来的最爱"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLOODSWORD = "不掉血多好啊"

STRINGS.NAMES.BLOODBLACKSWORD = "黑血刃"
STRINGS.RECIPE_DESC.BLOODBLACKSWORD = "来之不易啊"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLOODBLACKSWORD = "终于......"

STRINGS.NAMES.BLOODBLOWDART = "鲜红吹箭"
STRINGS.RECIPE_DESC.BLOODBLOWDART = "游击战"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLOODBLOWDART = "好伤！"

STRINGS.NAMES.GLASSES = "眼镜"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GLASSES = "卡哇伊"

STRINGS.NAMES.LSWLSSCARF = "未来的围巾"
STRINGS.RECIPE_DESC.LSWLSSCARF = "炒鸡保暖炒鸡萌"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LSWLSSCARF = "真希望这是学长送我的"

STRINGS.NAMES.BLOODBAT = "血器"
STRINGS.RECIPE_DESC.BLOODBAT = "实用的工具"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLOODBAT = "前期神器"

STRINGS.NAMES.SEALRING = "封印之戒"
STRINGS.RECIPE_DESC.SEALRING = "还原"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEALRING = "它居然封印了我的力量"  

STRINGS.NAMES.BLOODBOOK = "鲜血秘典"
STRINGS.RECIPE_DESC.BLOODBOOK = "还原"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLOODBOOK = "它无情的抽走我的血液"

STRINGS.NAMES.BLOODBOOK_REAP = "秘典·收割"
STRINGS.RECIPE_DESC.BLOODBOOK_REAP = "收获时间!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLOODBOOK_REAP = "真爽!"

STRINGS.NAMES.BLOODBOOK_SUMMON = "秘典·召唤"
STRINGS.RECIPE_DESC.BLOODBOOK_SUMMON = "这下有得玩了"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLOODBOOK_SUMMON = "不做死就不会死"

STRINGS.NAMES.BLOODBOOK_PLUS = "秘典·加强"
STRINGS.RECIPE_DESC.BLOODBOOK_PLUS = "更强力的效果"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLOODBOOK_PLUS = "我讨厌这玩意"

STRINGS.NAMES.EVILBLACKSTONE = "黑邪石"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.EVILBLACKSTONE = "这个战利品好像还不错"

STRINGS.NAMES.THECURSEBLOOD = "诅咒之血"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.THECURSEBLOOD = "这....这血里有毒"

STRINGS.NAMES.YM = "妖梦"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.YM = "我的勇士"

STRINGS.NAMES.DEERCLOPSBLACK = "虚无之影"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEERCLOPSBLACK = "黑恶势力登场！（别吐槽啊）"

STRINGS.RECIPE_DESC.REDGEM = "不科学的魔法"
STRINGS.RECIPE_DESC.BLUEGEM = "不科学的魔法"

STRINGS.NAMES.YMQUINTESSENCE = "妖梦精华"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.YMQUINTESSENCE = "合成妖梦石的必须材料"

STRINGS.LSWL_INTRO_MAXWELL_1 = "什么?!  你是谁?"
STRINGS.LSWL_INTRO_MAXWELL_2 = "你身上流淌着诅咒的血液!!"
STRINGS.LSWL_INTRO_MAXWELL_3 = "赶快离开!!!  这里不欢迎你!"

STRINGS.CHARACTER_TITLES.lswl = "栗山未来"
STRINGS.CHARACTER_NAMES.lswl = "栗山未来"
STRINGS.CHARACTER_DESCRIPTIONS.lswl = "*特有的鲜血能力\n*可以随着诅咒之力提高解锁能力\n*一个吃货,精神很不稳定,胆小怕黑"
STRINGS.CHARACTER_QUOTES.lswl = "\"我不愉快\""

STRINGS.TABS.BLOODTAB = "鲜血"